name: pattern_background
description: Create pattern background with diffrent shaps and customized sizes, colors and spacing. Enjoy!
version: 1.1.3
homepage: https://github.com/OmarHosamCodes/pattern-background-package

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
